const variableKeys = [
    // Basic
    "font-size",
    "line-height",
    "font-weight",
    "gap-size",
    "icon-size",
    "table-transition",
    // Color
    "border-color",
    "accent-color",
    "foreground-color",
    "background-color",
    "placeholder-color",
    "read-only-color",
    "disabled-color",
    // Border
    "cell-horizontal-border-color",
    "cell-vertical-border-color",
    // Wrapper
    "wrapper-border-width",
    "wrapper-border-radius",
    "wrapper-border-color",
    // Row odd and even
    "row-header-odd-background-color",
    "row-header-even-background-color",
    "row-cell-odd-background-color",
    "row-cell-even-background-color",
    // Cell padding
    "cell-horizontal-padding",
    "cell-vertical-padding",
    // Cell editor
    "cell-editor-border-width",
    "cell-editor-border-color",
    "cell-editor-foreground-color",
    "cell-editor-background-color",
    "cell-editor-shadow-blur-radius",
    "cell-editor-shadow-color",
    // Cell state
    "cell-success-background-color",
    "cell-error-background-color",
    // Cell selection
    "cell-selection-border-color",
    "cell-selection-background-color",
    // Cell autofill,
    "cell-autofill-size",
    "cell-autofill-border-width",
    "cell-autofill-border-radius",
    "cell-autofill-border-color",
    "cell-autofill-background-color",
    "cell-autofill-fill-border-color",
    // Resize indicator
    "resize-indicator-color",
    // Move
    "move-backlight-color",
    "move-indicator-color",
    // Hidden indicator 
    "hidden-indicator-color",
    // Scrollbar
    "scrollbar-border-radius",
    "scrollbar-track-color",
    "scrollbar-thumb-color",
    // Checkbox basic
    "checkbox-size",
    "checkbox-border-radius",
    "checkbox-border-color",
    "checkbox-background-color",
    "checkbox-icon-color",
    // Checkbox focus
    "checkbox-focus-border-color",
    "checkbox-focus-background-color",
    "checkbox-focus-icon-color",
    "checkbox-focus-ring-color",
    // Checkbox disabled
    "checkbox-disabled-border-color",
    "checkbox-disabled-background-color",
    "checkbox-disabled-icon-color",
    // Checkbox checked
    "checkbox-checked-border-color",
    "checkbox-checked-background-color",
    "checkbox-checked-icon-color",
    // Checkbox checked focus
    "checkbox-checked-focus-border-color",
    "checkbox-checked-focus-background-color",
    "checkbox-checked-focus-icon-color",
    // Checkbox checked disabled
    "checkbox-checked-disabled-border-color",
    "checkbox-checked-disabled-background-color",
    "checkbox-checked-disabled-icon-color",
    // Header
    "header-font-weight",
    "header-foreground-color",
    "header-background-color",
    "header-active-border-color",
    "header-active-foreground-color",
    "header-active-background-color",
    "header-highlighted-shadow-size",
    "header-highlighted-foreground-color",
    "header-highlighted-background-color",
    "header-filter-background-color",
    // Header row
    "header-row-foreground-color",
    "header-row-background-color",
    "header-row-highlighted-foreground-color",
    "header-row-highlighted-background-color",
    "header-row-active-foreground-color",
    "header-row-active-background-color",
    // Icon Button
    "icon-button-border-radius",
    "icon-button-border-color",
    "icon-button-background-color",
    "icon-button-icon-color",
    "icon-button-hover-border-color",
    "icon-button-hover-background-color",
    "icon-button-hover-icon-color",
    "icon-active-button-border-color",
    "icon-active-button-background-color",
    "icon-active-button-icon-color",
    "icon-active-button-hover-border-color",
    "icon-active-button-hover-background-color",
    "icon-active-button-hover-icon-color",
    // Collapse button
    "collapse-button-border-radius",
    "collapse-button-open-border-color",
    "collapse-button-open-background-color",
    "collapse-button-open-icon-color",
    "collapse-button-open-icon-active-color",
    "collapse-button-open-hover-border-color",
    "collapse-button-open-hover-background-color",
    "collapse-button-open-hover-icon-color",
    "collapse-button-open-hover-icon-active-color",
    "collapse-button-close-border-color",
    "collapse-button-close-background-color",
    "collapse-button-close-icon-color",
    "collapse-button-close-icon-active-color",
    "collapse-button-close-hover-border-color",
    "collapse-button-close-hover-background-color",
    "collapse-button-close-hover-icon-color",
    "collapse-button-close-hover-icon-active-color",
    // Button
    "button-border-radius",
    "button-horizontal-padding",
    "button-vertical-padding",
    "primary-button-border-color",
    "primary-button-foreground-color",
    "primary-button-background-color",
    "primary-button-disabled-border-color",
    "primary-button-disabled-foreground-color",
    "primary-button-disabled-background-color",
    "primary-button-hover-border-color",
    "primary-button-hover-foreground-color",
    "primary-button-hover-background-color",
    "primary-button-focus-border-color",
    "primary-button-focus-foreground-color",
    "primary-button-focus-background-color",
    "secondary-button-border-color",
    "secondary-button-foreground-color",
    "secondary-button-background-color",
    "secondary-button-disabled-border-color",
    "secondary-button-disabled-foreground-color",
    "secondary-button-disabled-background-color",
    "secondary-button-hover-border-color",
    "secondary-button-hover-foreground-color",
    "secondary-button-hover-background-color",
    "secondary-button-focus-border-color",
    "secondary-button-focus-foreground-color",
    "secondary-button-focus-background-color",
    // Comments
    "comments-textarea-horizontal-padding",
    "comments-textarea-vertical-padding",
    "comments-indicator-size",
    "comments-indicator-color",
    "comments-textarea-border-width",
    "comments-textarea-border-color",
    "comments-textarea-foreground-color",
    "comments-textarea-background-color",
    "comments-textarea-focus-border-width",
    "comments-textarea-focus-border-color",
    "comments-textarea-focus-foreground-color",
    "comments-textarea-focus-background-color",
    // License
    "license-horizontal-padding",
    "license-vertical-padding",
    "license-foreground-color",
    "license-background-color",
    // Link
    "link-color",
    "link-hover-color",
    // Input
    "input-border-width",
    "input-border-radius",
    "input-horizontal-padding",
    "input-vertical-padding",
    "input-border-color",
    "input-foreground-color",
    "input-background-color",
    "input-hover-border-color",
    "input-hover-foreground-color",
    "input-hover-background-color",
    "input-disabled-border-color",
    "input-disabled-foreground-color",
    "input-disabled-background-color",
    "input-focus-border-color",
    "input-focus-foreground-color",
    "input-focus-background-color",
    // Menu
    "menu-border-width",
    "menu-border-radius",
    "menu-horizontal-padding",
    "menu-vertical-padding",
    "menu-item-horizontal-padding",
    "menu-item-vertical-padding",
    "menu-shadow-x",
    "menu-shadow-y",
    "menu-shadow-blur",
    "menu-border-color",
    "menu-shadow-color",
    "menu-item-hover-color",
    "menu-item-active-color",
]

exports.variableKeys = variableKeys;
